version: '3.2'
services:
  web:
    container_name: phoenix-web
    image: elixir-phoenix
    build: .
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    ports:
      - 4040:4000
    volumes:
      - ./app:/app:delegated

  db:
    container_name: phoenix-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

networks:
  default:
    external:
      name: phoenix_network